# Create App Directory
# Build react client
FROM node:16.17.1
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install Dependencies
COPY package*.json ./

RUN npm install --silent

# Copy app source code
COPY . .

# Exports
EXPOSE 8081

CMD ["node","app.js"]